sudo: required
os: linux
dist: trusty
services:
  - docker

language: java
jdk:
 - oraclejdk11 # This is needed in order to have a $HOME/.m2 directory already set up

install: true

env:
  global:
    - DOCKER_COMPOSE_VERSION="1.23.2"
  
cache:
  directories:
  - /usr/local/bin
  - /usr/bin
  - $HOME/.travis_cache
  - $HOME/.m2 # Maven will download dependencies to this folder
  - ./user-manager/user-manager-rest-api/node_modules # Node.js dependencies

# matrix:
#   fast_finish: true

addons:
  apt:
    packages:
      - docker-ce # updates Docker

before_install:
  # shows the current version of docker
  - docker --version
  # install the version of docker-compose identified by $DOCKER_COMPOSE_VERSION
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
  - sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
  - sudo chmod +x /usr/bin/docker-compose
  # shows the current version of docker-compose
  - docker-compose --version
  # makes the shell files executable
  - find ./ -type f -name "*.sh" -exec chmod +x {} \;
  # install project dependencies
  - ./install.sh

script:
  # tests the Java services and the User Manager
  - ./test.sh
