version: '3.5'

services:
  postgres-test:
    image: "postgres:11-alpine"
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      # for the test database, no demo data should be inserted
      - ./user-manager-database/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      POSTGRES_PASSWORD: "butterfly_user"
      POSTGRES_USER: "butterfly_user"
      POSTGRES_DB: "butterfly"
    networks:
      - user-manager-test-network

  staging:
    image: node:10.15.3-alpine
    volumes:
      - ./user-manager-rest-api:/usr/app
    working_dir: /usr/app
    restart: "no"
    ports:
      - "5000:5000"
    depends_on:
      - postgres-test
    env_file: ./user-manager-rest-api/.user-manager-rest-api.env
    environment:
      NODE_ENV: "test"
      DATABASE_HOST: "postgres-test"
    networks:
      - user-manager-test-network
    entrypoint:
      - yarn
      - test:ci

networks:
  user-manager-test-network:
    name: user-manager-test-network