version: '3.5'

services:
  pgadmin:
    image: "dpage/pgadmin4:latest"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./user-manager-database/pgadmin/servers.json:/pgadmin4/servers.json
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    depends_on:
      - postgres
    networks:
      - user-manager-network

  postgres:
    image: "postgres:11-alpine"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      # for the production database, no demo data should be inserted
      - ./user-manager-database/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "butterfly_user"
      POSTGRES_USER: "butterfly_user"
      POSTGRES_DB: "butterfly"
    networks:
      - user-manager-network

  user-manager:
    build:
      context: ./user-manager-rest-api
    restart: always
    ports:
      - "5000:5000"
    links:
      - postgres
    depends_on:
      - postgres
    env_file: ./user-manager-rest-api/.user-manager-rest-api.env
    environment:
      NODE_ENV: "production"
    networks:
      - user-manager-network
      # - middleware-dispatcher-network

volumes:
  pg_data:

networks:
  user-manager-network:
    name: user-manager-network
  # middleware-dispatcher-network:
  #   external:
  #     name: middleware-dispatcher-network