version: '3.5'

services:
  postgres-test:
    image: "postgres:11-alpine"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      # for the test database, no demo data should be inserted
      - ./user-manager-database/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - pg_test_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "butterfly_user"
      POSTGRES_USER: "butterfly_user"
      POSTGRES_DB: "butterfly"
    networks:
      - user-manager-network

  user-manager:
    build:
      context: ./user-manager-rest-api
    restart: "no"
    ports:
      - "5000:5000"
    links:
      # 'postgres' will be an alias for the 'postgres-test' service
      - postgres-test:postgres
    depends_on:
      - postgres-test
    env_file: ./user-manager-rest-api/.user-manager-rest-api.env
    environment:
      NODE_ENV: "test"
    networks:
      - user-manager-network
      - middleware-dispatcher-network
    entrypoint:
      - npm
      - test

volumes:
  pg_test_data:

networks:
  user-manager-network:
    name: user-manager-network
  middleware-dispatcher-network:
    external:
      name: middleware-dispatcher-network