version: '3.5'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./user-manager-rest-api/openapi/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    networks:
      - user-manager-network
      - swagger

  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: user-manager-pgadmin
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./user-manager-database/pgadmin/servers.json:/pgadmin4/servers.json
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    depends_on:
      - postgres
    networks:
      - user-manager-network

networks:
  swagger:
    name: swagger